// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpitchshift.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPitchshift_CfgInitialize(XPitchshift *InstancePtr, XPitchshift_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPitchshift_Start(XPitchshift *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL) & 0x80;
    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPitchshift_IsDone(XPitchshift *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPitchshift_IsIdle(XPitchshift *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPitchshift_IsReady(XPitchshift *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPitchshift_EnableAutoRestart(XPitchshift *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL, 0x80);
}

void XPitchshift_DisableAutoRestart(XPitchshift *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_AP_CTRL, 0);
}

void XPitchshift_Set_Len(XPitchshift *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_LEN_DATA, Data);
}

u32 XPitchshift_Get_Len(XPitchshift *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_LEN_DATA);
    return Data;
}

void XPitchshift_InterruptGlobalEnable(XPitchshift *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_GIE, 1);
}

void XPitchshift_InterruptGlobalDisable(XPitchshift *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_GIE, 0);
}

void XPitchshift_InterruptEnable(XPitchshift *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_IER);
    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_IER, Register | Mask);
}

void XPitchshift_InterruptDisable(XPitchshift *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_IER);
    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_IER, Register & (~Mask));
}

void XPitchshift_InterruptClear(XPitchshift *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPitchshift_WriteReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_ISR, Mask);
}

u32 XPitchshift_InterruptGetEnabled(XPitchshift *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_IER);
}

u32 XPitchshift_InterruptGetStatus(XPitchshift *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPitchshift_ReadReg(InstancePtr->Ctrl_BaseAddress, XPITCHSHIFT_CTRL_ADDR_ISR);
}

