// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPITCHSHIFT_H
#define XPITCHSHIFT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpitchshift_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_BaseAddress;
} XPitchshift_Config;
#endif

typedef struct {
    u32 Ctrl_BaseAddress;
    u32 IsReady;
} XPitchshift;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPitchshift_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPitchshift_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPitchshift_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPitchshift_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPitchshift_Initialize(XPitchshift *InstancePtr, u16 DeviceId);
XPitchshift_Config* XPitchshift_LookupConfig(u16 DeviceId);
int XPitchshift_CfgInitialize(XPitchshift *InstancePtr, XPitchshift_Config *ConfigPtr);
#else
int XPitchshift_Initialize(XPitchshift *InstancePtr, const char* InstanceName);
int XPitchshift_Release(XPitchshift *InstancePtr);
#endif

void XPitchshift_Start(XPitchshift *InstancePtr);
u32 XPitchshift_IsDone(XPitchshift *InstancePtr);
u32 XPitchshift_IsIdle(XPitchshift *InstancePtr);
u32 XPitchshift_IsReady(XPitchshift *InstancePtr);
void XPitchshift_EnableAutoRestart(XPitchshift *InstancePtr);
void XPitchshift_DisableAutoRestart(XPitchshift *InstancePtr);

void XPitchshift_Set_Len(XPitchshift *InstancePtr, u32 Data);
u32 XPitchshift_Get_Len(XPitchshift *InstancePtr);

void XPitchshift_InterruptGlobalEnable(XPitchshift *InstancePtr);
void XPitchshift_InterruptGlobalDisable(XPitchshift *InstancePtr);
void XPitchshift_InterruptEnable(XPitchshift *InstancePtr, u32 Mask);
void XPitchshift_InterruptDisable(XPitchshift *InstancePtr, u32 Mask);
void XPitchshift_InterruptClear(XPitchshift *InstancePtr, u32 Mask);
u32 XPitchshift_InterruptGetEnabled(XPitchshift *InstancePtr);
u32 XPitchshift_InterruptGetStatus(XPitchshift *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
