// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpitchshift.h"

extern XPitchshift_Config XPitchshift_ConfigTable[];

XPitchshift_Config *XPitchshift_LookupConfig(u16 DeviceId) {
	XPitchshift_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPITCHSHIFT_NUM_INSTANCES; Index++) {
		if (XPitchshift_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPitchshift_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPitchshift_Initialize(XPitchshift *InstancePtr, u16 DeviceId) {
	XPitchshift_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPitchshift_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPitchshift_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

