// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtestloop.h"

extern XTestloop_Config XTestloop_ConfigTable[];

XTestloop_Config *XTestloop_LookupConfig(u16 DeviceId) {
	XTestloop_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTESTLOOP_NUM_INSTANCES; Index++) {
		if (XTestloop_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTestloop_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTestloop_Initialize(XTestloop *InstancePtr, u16 DeviceId) {
	XTestloop_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTestloop_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTestloop_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

