// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        t_in,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    ap_const_lv32_0 = 32'd0;




input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [63:0] t_in;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] ref_4oPi_table_256_V_address0;
reg    ref_4oPi_table_256_V_ce0;
wire   [255:0] ref_4oPi_table_256_V_q0;
wire   [7:0] fourth_order_double_4_address0;
reg    fourth_order_double_4_ce0;
wire   [58:0] fourth_order_double_4_q0;
wire   [7:0] fourth_order_double_5_address0;
reg    fourth_order_double_5_ce0;
wire   [51:0] fourth_order_double_5_q0;
wire   [7:0] fourth_order_double_6_address0;
reg    fourth_order_double_6_ce0;
wire   [43:0] fourth_order_double_6_q0;
wire   [7:0] fourth_order_double_7_address0;
reg    fourth_order_double_7_ce0;
wire   [32:0] fourth_order_double_7_q0;
wire   [7:0] fourth_order_double_s_address0;
reg    fourth_order_double_s_ce0;
wire   [24:0] fourth_order_double_s_q0;
reg   [0:0] p_Result_30_reg_1493;
reg   [0:0] p_Result_30_reg_1493_pp0_iter1_reg;
reg   [0:0] p_Result_30_reg_1493_pp0_iter2_reg;
reg   [0:0] p_Result_30_reg_1493_pp0_iter3_reg;
reg   [0:0] p_Result_30_reg_1493_pp0_iter4_reg;
reg   [0:0] p_Result_30_reg_1493_pp0_iter5_reg;
reg   [0:0] p_Result_30_reg_1493_pp0_iter6_reg;
wire   [10:0] loc_V_fu_314_p4;
reg   [10:0] loc_V_reg_1498;
reg   [10:0] loc_V_reg_1498_pp0_iter1_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter2_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter3_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter4_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter5_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter6_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter7_reg;
reg   [10:0] loc_V_reg_1498_pp0_iter8_reg;
wire   [51:0] loc_V_1_fu_324_p1;
reg   [51:0] loc_V_1_reg_1505;
reg   [51:0] loc_V_1_reg_1505_pp0_iter1_reg;
wire   [0:0] closepath_fu_328_p2;
reg   [0:0] closepath_reg_1511;
reg   [0:0] closepath_reg_1511_pp0_iter1_reg;
reg   [0:0] closepath_reg_1511_pp0_iter2_reg;
reg   [0:0] closepath_reg_1511_pp0_iter3_reg;
reg   [0:0] closepath_reg_1511_pp0_iter4_reg;
reg   [0:0] closepath_reg_1511_pp0_iter5_reg;
reg   [0:0] closepath_reg_1511_pp0_iter6_reg;
reg   [0:0] closepath_reg_1511_pp0_iter7_reg;
reg   [0:0] closepath_reg_1511_pp0_iter8_reg;
wire   [6:0] tmp_20_fu_363_p1;
reg   [6:0] tmp_20_reg_1522;
reg   [169:0] ret_V_reg_1527;
wire   [0:0] tmp_4_fu_406_p2;
reg   [0:0] tmp_4_reg_1542;
reg   [0:0] tmp_4_reg_1542_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_1542_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_1542_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_1542_pp0_iter6_reg;
reg   [123:0] p_Val2_8_reg_1548;
reg   [2:0] tmp_11_i_reg_1554;
wire   [123:0] p_Val2_9_fu_446_p3;
reg   [123:0] p_Val2_9_reg_1559;
reg   [123:0] p_Val2_9_reg_1559_pp0_iter8_reg;
reg   [60:0] p_Result_i2_i_reg_1564;
wire   [0:0] sin_basis_fu_463_p10;
reg   [0:0] sin_basis_reg_1569;
reg   [0:0] sin_basis_reg_1569_pp0_iter8_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter9_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter10_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter11_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter12_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter13_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter14_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter15_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter16_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter17_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter18_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter19_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter20_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter21_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter22_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter23_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter24_reg;
reg   [0:0] sin_basis_reg_1569_pp0_iter25_reg;
wire   [0:0] or_cond_44_fu_581_p2;
reg   [0:0] or_cond_44_reg_1576;
reg   [0:0] or_cond_44_reg_1576_pp0_iter8_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter9_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter10_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter11_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter12_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter13_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter14_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter15_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter16_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter17_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter18_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter19_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter20_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter21_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter22_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter23_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter24_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter25_reg;
reg   [0:0] or_cond_44_reg_1576_pp0_iter26_reg;
wire   [0:0] tmp_5_fu_586_p2;
reg   [0:0] tmp_5_reg_1583;
reg   [0:0] tmp_5_reg_1583_pp0_iter8_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter9_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter10_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter11_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter12_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter13_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter14_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter15_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter16_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter17_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter18_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter19_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter20_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter21_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter22_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter23_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter24_reg;
reg   [0:0] tmp_5_reg_1583_pp0_iter25_reg;
wire   [0:0] p_Result_s_fu_614_p2;
reg   [0:0] p_Result_s_reg_1588;
reg   [0:0] p_Result_s_reg_1588_pp0_iter8_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter9_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter10_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter11_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter12_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter13_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter14_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter15_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter16_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter17_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter18_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter19_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter20_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter21_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter22_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter23_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter24_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter25_reg;
reg   [0:0] p_Result_s_reg_1588_pp0_iter26_reg;
wire   [5:0] Mx_zeros_V_fu_653_p1;
reg   [5:0] Mx_zeros_V_reg_1593;
reg   [62:0] Mx_V_reg_1599;
reg   [62:0] Mx_V_reg_1599_pp0_iter10_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter11_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter12_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter13_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter14_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter15_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter16_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter17_reg;
reg   [62:0] Mx_V_reg_1599_pp0_iter18_reg;
wire  signed [10:0] Ex_V_fu_690_p2;
reg  signed [10:0] Ex_V_reg_1606;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter10_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter11_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter12_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter13_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter14_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter15_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter16_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter17_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter18_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter19_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter20_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter21_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter22_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter23_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter24_reg;
reg  signed [10:0] Ex_V_reg_1606_pp0_iter25_reg;
reg   [0:0] isNeg_reg_1612;
reg   [6:0] p_Result_i_reg_1618;
reg   [6:0] p_Result_i_reg_1618_pp0_iter11_reg;
reg   [6:0] p_Result_i_reg_1618_pp0_iter12_reg;
wire   [55:0] p_Val2_16_fu_755_p1;
reg   [55:0] p_Val2_16_reg_1623;
reg   [55:0] p_Val2_16_reg_1623_pp0_iter11_reg;
reg   [55:0] p_Val2_16_reg_1623_pp0_iter12_reg;
reg   [55:0] p_Val2_16_reg_1623_pp0_iter13_reg;
reg   [55:0] p_Val2_16_reg_1623_pp0_iter14_reg;
reg   [48:0] tmp_i1_reg_1628;
wire   [97:0] OP1_V_fu_769_p1;
reg   [97:0] OP1_V_reg_1633;
reg   [97:0] OP1_V_reg_1633_pp0_iter12_reg;
reg   [48:0] tmp_37_i_reg_1640;
reg   [48:0] tmp_37_i_reg_1640_pp0_iter13_reg;
reg   [48:0] tmp_37_i_reg_1640_pp0_iter14_reg;
wire   [97:0] OP2_V_fu_788_p1;
reg   [41:0] tmp_39_i_reg_1678;
reg   [34:0] tmp_41_i_reg_1683;
reg   [58:0] p_Val2_20_reg_1688;
reg   [58:0] p_Val2_20_reg_1688_pp0_iter15_reg;
reg   [58:0] p_Val2_20_reg_1688_pp0_iter16_reg;
reg   [58:0] p_Val2_20_reg_1688_pp0_iter17_reg;
reg  signed [51:0] fourth_order_double_10_reg_1693;
reg  signed [43:0] fourth_order_double_12_reg_1698;
reg   [32:0] fourth_order_double_14_reg_1703;
reg   [24:0] fourth_order_double_16_reg_1708;
reg   [28:0] tmp_s_reg_1743;
reg   [28:0] tmp_s_reg_1743_pp0_iter16_reg;
reg   [55:0] tmp_8_i_reg_1748;
reg   [55:0] tmp_8_i_reg_1748_pp0_iter17_reg;
reg   [47:0] tmp_10_i1_reg_1753;
reg   [36:0] tmp_1_reg_1758;
wire   [48:0] tmp8_fu_944_p2;
reg   [48:0] tmp8_reg_1763;
wire   [63:0] r_V_fu_973_p2;
reg  signed [63:0] r_V_reg_1768;
reg   [62:0] result_V_reg_1783;
reg   [15:0] p_Result_1_i_reg_1788;
reg   [15:0] p_Result_13_1_i_reg_1793;
reg   [15:0] p_Result_13_1_i_reg_1793_pp0_iter24_reg;
reg   [15:0] p_Result_13_2_i_reg_1798;
reg   [15:0] p_Result_13_2_i_reg_1798_pp0_iter24_reg;
reg   [14:0] p_Result_i1_reg_1803;
reg   [14:0] p_Result_i1_reg_1803_pp0_iter24_reg;
reg   [61:0] in_V_cast_i_reg_1808;
reg   [31:0] tmp_i_i_fu_1087_p3;
reg   [31:0] tmp_i_i_reg_1813;
reg   [31:0] tmp_i_i_reg_1813_pp0_iter25_reg;
wire   [61:0] tmp_8_i4_fu_1099_p2;
reg   [61:0] tmp_8_i4_reg_1819;
reg   [61:0] tmp_8_i4_reg_1819_pp0_iter25_reg;
reg   [61:0] tmp_8_i4_reg_1819_pp0_iter26_reg;
wire   [0:0] tmp_9_i7_fu_1104_p2;
reg   [0:0] tmp_9_i7_reg_1825;
reg   [0:0] tmp_9_i7_reg_1825_pp0_iter25_reg;
reg   [31:0] tmp_i2_i_fu_1194_p3;
reg   [31:0] tmp_i2_i_reg_1830;
reg   [31:0] tmp_i3_i3_fu_1212_p3;
reg   [31:0] tmp_i3_i3_reg_1836;
reg   [31:0] tmp_i3_i3_reg_1836_pp0_iter26_reg;
wire   [31:0] shift_2_1_i_fu_1220_p2;
reg   [31:0] shift_2_1_i_reg_1842;
wire   [61:0] tmp_8_1_i_fu_1230_p2;
reg   [61:0] tmp_8_1_i_reg_1847;
reg   [61:0] tmp_8_1_i_reg_1847_pp0_iter26_reg;
wire   [0:0] tmp_10_1_i_fu_1235_p2;
reg   [0:0] tmp_10_1_i_reg_1853;
wire   [31:0] shift_2_2_i_fu_1241_p2;
reg   [31:0] shift_2_2_i_reg_1859;
wire   [0:0] tmp_i5_fu_1257_p2;
reg   [0:0] tmp_i5_reg_1865;
wire   [61:0] tmp_8_2_i_fu_1265_p2;
reg   [61:0] tmp_8_2_i_reg_1870;
wire   [0:0] sel_tmp6_i_fu_1295_p2;
reg   [0:0] sel_tmp6_i_reg_1876;
wire   [0:0] or_cond_fu_1301_p2;
reg   [0:0] or_cond_reg_1881;
wire   [0:0] or_cond_i_fu_1352_p2;
reg   [0:0] or_cond_i_reg_1886;
wire   [0:0] tmp_9_fu_1376_p2;
reg   [0:0] tmp_9_reg_1891;
wire   [10:0] ret_V_9_fu_1380_p3;
reg   [10:0] ret_V_9_reg_1896;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] tmp_2_i_i_fu_358_p1;
wire   [63:0] tmp_42_i_fu_808_p1;
wire   [63:0] p_Val2_s_fu_302_p1;
wire   [10:0] expv_op_fu_334_p2;
wire   [10:0] addr_V_fu_340_p3;
wire   [3:0] p_Result_i_i_fu_348_p4;
wire   [255:0] tmp_4_i_i_fu_367_p1;
wire   [255:0] r_V_3_fu_370_p2;
wire   [52:0] p_Result_31_fu_386_p3;
wire   [52:0] grp_fu_400_p0;
wire   [169:0] grp_fu_400_p1;
wire   [222:0] grp_fu_400_p2;
wire   [2:0] p_Val2_34_fu_431_p3;
wire   [0:0] tmp_21_fu_437_p1;
wire   [123:0] p_Val2_i_fu_441_p2;
wire   [3:0] p_Result_41_fu_485_p3;
wire   [0:0] tmp_6_fu_492_p18;
wire   [0:0] tmp_7_fu_530_p18;
wire   [0:0] tmp_3_fu_576_p2;
wire   [0:0] tmp_2_fu_568_p3;
wire   [0:0] tmp_8_fu_591_p2;
wire   [0:0] not_or_cond_demorgan_fu_603_p2;
wire   [0:0] p_results_sign_V_ret_fu_597_p2;
wire   [0:0] not_or_cond_fu_608_p2;
wire   [61:0] p_Result_32_fu_620_p3;
reg   [61:0] p_Result_33_fu_627_p4;
wire   [63:0] p_Result_34_fu_637_p3;
reg   [63:0] tmp_i3_i_fu_645_p3;
wire   [10:0] tmp_i_fu_657_p2;
wire   [123:0] tmp_12_i_fu_669_p1;
wire   [123:0] p_Val2_14_fu_672_p2;
wire   [10:0] storemerge_i_fu_662_p3;
wire   [10:0] tmp_15_i_fu_687_p1;
wire  signed [11:0] sh_i_cast_fu_704_p1;
wire   [11:0] tmp_17_i_fu_707_p2;
wire   [11:0] sh_assign_fu_713_p3;
wire  signed [31:0] sh_assign_1_i_cast_fu_720_p1;
wire   [62:0] tmp_18_i_fu_724_p1;
wire   [62:0] tmp_19_i_fu_728_p2;
wire   [62:0] tmp_20_i_fu_733_p2;
wire   [62:0] p_Val2_15_fu_738_p3;
wire   [48:0] grp_fu_772_p0;
wire   [48:0] grp_fu_772_p1;
wire   [97:0] grp_fu_772_p2;
wire   [48:0] grp_fu_791_p0;
wire   [48:0] grp_fu_791_p1;
wire   [48:0] grp_fu_796_p0;
wire   [48:0] grp_fu_796_p1;
wire   [7:0] p_Result_35_fu_802_p3;
wire   [97:0] grp_fu_791_p2;
wire   [97:0] grp_fu_796_p2;
wire   [55:0] grp_fu_843_p1;
wire   [48:0] grp_fu_855_p1;
wire   [32:0] grp_fu_867_p0;
wire   [41:0] grp_fu_867_p1;
wire   [24:0] p_Val2_2_fu_879_p0;
wire   [34:0] p_Val2_2_fu_879_p1;
wire   [59:0] p_Val2_2_fu_879_p2;
wire   [107:0] grp_fu_843_p2;
wire   [92:0] grp_fu_855_p2;
wire   [74:0] grp_fu_867_p2;
wire   [37:0] tmp_51_i_cast_cast_fu_931_p1;
wire   [37:0] tmp_12_i1_fu_925_p1;
wire   [37:0] tmp9_fu_934_p2;
wire  signed [48:0] tmp_47_i_cast_cast_fu_928_p1;
wire   [48:0] tmp9_cast_fu_940_p1;
wire   [62:0] p_Val2_21_fu_950_p3;
wire  signed [63:0] tmp_45_i_fu_961_p1;
wire  signed [63:0] tmp_44_i_fu_957_p1;
wire   [63:0] tmp_fu_964_p2;
wire  signed [63:0] tmp8_cast_fu_970_p1;
wire   [62:0] Mx_V_read_assign_fu_979_p3;
wire   [62:0] grp_fu_992_p0;
wire   [125:0] grp_fu_992_p2;
wire   [16:0] tmp_i_43_fu_1058_p3;
wire   [31:0] p_Val2_24_fu_1065_p5;
reg   [31:0] p_Result_37_fu_1077_p4;
wire   [61:0] tmp_4_cast_i_fu_1095_p1;
wire   [16:0] tmp_1_i_fu_1109_p3;
wire   [16:0] tmp_2_i_fu_1128_p3;
wire   [15:0] tmp_3_i_fu_1147_p3;
wire   [31:0] p_Val2_25_fu_1116_p5;
reg   [31:0] p_Result_38_fu_1166_p4;
wire   [31:0] p_Val2_26_fu_1135_p5;
reg   [31:0] p_Result_39_fu_1184_p4;
wire   [31:0] p_Result_36_fu_1154_p5;
reg   [31:0] p_Result_40_fu_1202_p4;
reg   [31:0] tmp_i1_i_fu_1176_p3;
wire   [61:0] tmp_4_1_cast_i_fu_1226_p1;
wire   [10:0] Ex_V_ret_s_fu_1247_p3;
wire   [61:0] tmp_4_2_cast_i_fu_1262_p1;
wire   [0:0] sel_tmp2_i_fu_1279_p2;
wire   [0:0] tmp_10_2_i_fu_1270_p2;
wire   [0:0] tmp2_fu_1290_p2;
wire   [0:0] sel_tmp3_i_fu_1284_p2;
wire   [31:0] shift_2_3_i_fu_1275_p2;
wire   [31:0] newSel3_fu_1307_p3;
wire   [31:0] newSel4_fu_1314_p3;
wire  signed [11:0] rhs_V_fu_1253_p1;
wire   [11:0] tmp_6_i_fu_1328_p2;
wire  signed [31:0] tmp_6_cast_i_fu_1334_p1;
wire   [31:0] newSel5_fu_1320_p3;
wire   [31:0] newexp_fu_1338_p2;
wire   [0:0] tmp_25_fu_1344_p3;
wire   [10:0] tmp_26_fu_1357_p1;
wire   [10:0] p_results_exp_V_ret_fu_1369_p3;
wire   [10:0] out_exp_V_fu_1361_p3;
wire   [61:0] tmp_4_3_cast_i_fu_1388_p1;
wire   [61:0] tmp_8_3_i_fu_1391_p2;
wire   [51:0] tmp_10_fu_1396_p4;
wire   [51:0] tmp_11_fu_1406_p4;
wire   [51:0] tmp_13_fu_1422_p4;
wire   [51:0] tmp_14_fu_1431_p4;
wire   [51:0] tmp_12_fu_1415_p3;
wire   [51:0] tmp_15_fu_1440_p3;
wire   [51:0] tmp_16_fu_1447_p3;
wire   [0:0] not_or_cond1_fu_1461_p2;
wire   [51:0] p_results_sig_V_ret_c_fu_1466_p3;
wire   [51:0] p_Val2_35_fu_1454_p3;
wire   [51:0] ret_V_10_fu_1474_p3;
wire   [63:0] p_Result_42_fu_1481_p4;
reg    grp_fu_400_ce;
reg    grp_fu_772_ce;
reg    grp_fu_791_ce;
reg    grp_fu_796_ce;
reg    grp_fu_843_ce;
reg    grp_fu_855_ce;
reg    grp_fu_867_ce;
reg    grp_fu_992_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to26;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [222:0] grp_fu_400_p00;
wire   [222:0] grp_fu_400_p10;
wire   [107:0] grp_fu_843_p10;
wire   [92:0] grp_fu_855_p10;
wire   [74:0] grp_fu_867_p00;
wire   [74:0] grp_fu_867_p10;
wire   [125:0] grp_fu_992_p00;
wire   [59:0] p_Val2_2_fu_879_p00;
wire   [59:0] p_Val2_2_fu_879_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
end

sin_or_cos_doublebkb #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ref_4oPi_table_256_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_256_V_address0),
    .ce0(ref_4oPi_table_256_V_ce0),
    .q0(ref_4oPi_table_256_V_q0)
);

sin_or_cos_doublecud #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_4_address0),
    .ce0(fourth_order_double_4_ce0),
    .q0(fourth_order_double_4_q0)
);

sin_or_cos_doubledEe #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_5_address0),
    .ce0(fourth_order_double_5_ce0),
    .q0(fourth_order_double_5_q0)
);

sin_or_cos_doubleeOg #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_6_address0),
    .ce0(fourth_order_double_6_ce0),
    .q0(fourth_order_double_6_q0)
);

sin_or_cos_doublefYi #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_7_address0),
    .ce0(fourth_order_double_7_ce0),
    .q0(fourth_order_double_7_q0)
);

sin_or_cos_doubleg8j #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_s_address0),
    .ce0(fourth_order_double_s_ce0),
    .q0(fourth_order_double_s_q0)
);

pitchshift_mul_53hbi #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 53 ),
    .din1_WIDTH( 170 ),
    .dout_WIDTH( 223 ))
pitchshift_mul_53hbi_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_400_p0),
    .din1(grp_fu_400_p1),
    .ce(grp_fu_400_ce),
    .dout(grp_fu_400_p2)
);

pitchshift_mux_83ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
pitchshift_mux_83ibs_U2(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(p_Val2_34_fu_431_p3),
    .dout(sin_basis_fu_463_p10)
);

pitchshift_mux_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
pitchshift_mux_16jbC_U3(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_41_fu_485_p3),
    .dout(tmp_6_fu_492_p18)
);

pitchshift_mux_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
pitchshift_mux_16jbC_U4(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_41_fu_485_p3),
    .dout(tmp_7_fu_530_p18)
);

pitchshift_mul_49kbM #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
pitchshift_mul_49kbM_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_772_p0),
    .din1(grp_fu_772_p1),
    .ce(grp_fu_772_ce),
    .dout(grp_fu_772_p2)
);

pitchshift_mul_49kbM #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
pitchshift_mul_49kbM_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_791_p0),
    .din1(grp_fu_791_p1),
    .ce(grp_fu_791_ce),
    .dout(grp_fu_791_p2)
);

pitchshift_mul_49kbM #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
pitchshift_mul_49kbM_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_796_p0),
    .din1(grp_fu_796_p1),
    .ce(grp_fu_796_ce),
    .dout(grp_fu_796_p2)
);

pitchshift_mul_52lbW #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 52 ),
    .din1_WIDTH( 56 ),
    .dout_WIDTH( 108 ))
pitchshift_mul_52lbW_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fourth_order_double_10_reg_1693),
    .din1(grp_fu_843_p1),
    .ce(grp_fu_843_ce),
    .dout(grp_fu_843_p2)
);

pitchshift_mul_44mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 93 ))
pitchshift_mul_44mb6_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fourth_order_double_12_reg_1698),
    .din1(grp_fu_855_p1),
    .ce(grp_fu_855_ce),
    .dout(grp_fu_855_p2)
);

pitchshift_mul_33ncg #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 42 ),
    .dout_WIDTH( 75 ))
pitchshift_mul_33ncg_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_867_p0),
    .din1(grp_fu_867_p1),
    .ce(grp_fu_867_ce),
    .dout(grp_fu_867_p2)
);

pitchshift_mul_63ocq #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 126 ))
pitchshift_mul_63ocq_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_992_p0),
    .din1(r_V_reg_1768),
    .ce(grp_fu_992_ce),
    .dout(grp_fu_992_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ex_V_reg_1606 <= Ex_V_fu_690_p2;
        Ex_V_reg_1606_pp0_iter10_reg <= Ex_V_reg_1606;
        Ex_V_reg_1606_pp0_iter11_reg <= Ex_V_reg_1606_pp0_iter10_reg;
        Ex_V_reg_1606_pp0_iter12_reg <= Ex_V_reg_1606_pp0_iter11_reg;
        Ex_V_reg_1606_pp0_iter13_reg <= Ex_V_reg_1606_pp0_iter12_reg;
        Ex_V_reg_1606_pp0_iter14_reg <= Ex_V_reg_1606_pp0_iter13_reg;
        Ex_V_reg_1606_pp0_iter15_reg <= Ex_V_reg_1606_pp0_iter14_reg;
        Ex_V_reg_1606_pp0_iter16_reg <= Ex_V_reg_1606_pp0_iter15_reg;
        Ex_V_reg_1606_pp0_iter17_reg <= Ex_V_reg_1606_pp0_iter16_reg;
        Ex_V_reg_1606_pp0_iter18_reg <= Ex_V_reg_1606_pp0_iter17_reg;
        Ex_V_reg_1606_pp0_iter19_reg <= Ex_V_reg_1606_pp0_iter18_reg;
        Ex_V_reg_1606_pp0_iter20_reg <= Ex_V_reg_1606_pp0_iter19_reg;
        Ex_V_reg_1606_pp0_iter21_reg <= Ex_V_reg_1606_pp0_iter20_reg;
        Ex_V_reg_1606_pp0_iter22_reg <= Ex_V_reg_1606_pp0_iter21_reg;
        Ex_V_reg_1606_pp0_iter23_reg <= Ex_V_reg_1606_pp0_iter22_reg;
        Ex_V_reg_1606_pp0_iter24_reg <= Ex_V_reg_1606_pp0_iter23_reg;
        Ex_V_reg_1606_pp0_iter25_reg <= Ex_V_reg_1606_pp0_iter24_reg;
        Mx_V_reg_1599 <= {{p_Val2_14_fu_672_p2[123:61]}};
        Mx_V_reg_1599_pp0_iter10_reg <= Mx_V_reg_1599;
        Mx_V_reg_1599_pp0_iter11_reg <= Mx_V_reg_1599_pp0_iter10_reg;
        Mx_V_reg_1599_pp0_iter12_reg <= Mx_V_reg_1599_pp0_iter11_reg;
        Mx_V_reg_1599_pp0_iter13_reg <= Mx_V_reg_1599_pp0_iter12_reg;
        Mx_V_reg_1599_pp0_iter14_reg <= Mx_V_reg_1599_pp0_iter13_reg;
        Mx_V_reg_1599_pp0_iter15_reg <= Mx_V_reg_1599_pp0_iter14_reg;
        Mx_V_reg_1599_pp0_iter16_reg <= Mx_V_reg_1599_pp0_iter15_reg;
        Mx_V_reg_1599_pp0_iter17_reg <= Mx_V_reg_1599_pp0_iter16_reg;
        Mx_V_reg_1599_pp0_iter18_reg <= Mx_V_reg_1599_pp0_iter17_reg;
        Mx_zeros_V_reg_1593 <= Mx_zeros_V_fu_653_p1;
        OP1_V_reg_1633[48 : 0] <= OP1_V_fu_769_p1[48 : 0];
        OP1_V_reg_1633_pp0_iter12_reg[48 : 0] <= OP1_V_reg_1633[48 : 0];
        closepath_reg_1511_pp0_iter2_reg <= closepath_reg_1511_pp0_iter1_reg;
        closepath_reg_1511_pp0_iter3_reg <= closepath_reg_1511_pp0_iter2_reg;
        closepath_reg_1511_pp0_iter4_reg <= closepath_reg_1511_pp0_iter3_reg;
        closepath_reg_1511_pp0_iter5_reg <= closepath_reg_1511_pp0_iter4_reg;
        closepath_reg_1511_pp0_iter6_reg <= closepath_reg_1511_pp0_iter5_reg;
        closepath_reg_1511_pp0_iter7_reg <= closepath_reg_1511_pp0_iter6_reg;
        closepath_reg_1511_pp0_iter8_reg <= closepath_reg_1511_pp0_iter7_reg;
        fourth_order_double_10_reg_1693 <= fourth_order_double_5_q0;
        fourth_order_double_12_reg_1698 <= fourth_order_double_6_q0;
        fourth_order_double_14_reg_1703 <= fourth_order_double_7_q0;
        fourth_order_double_16_reg_1708 <= fourth_order_double_s_q0;
        in_V_cast_i_reg_1808 <= {{grp_fu_992_p2[124:63]}};
        isNeg_reg_1612 <= Ex_V_fu_690_p2[32'd10];
        loc_V_reg_1498_pp0_iter2_reg <= loc_V_reg_1498_pp0_iter1_reg;
        loc_V_reg_1498_pp0_iter3_reg <= loc_V_reg_1498_pp0_iter2_reg;
        loc_V_reg_1498_pp0_iter4_reg <= loc_V_reg_1498_pp0_iter3_reg;
        loc_V_reg_1498_pp0_iter5_reg <= loc_V_reg_1498_pp0_iter4_reg;
        loc_V_reg_1498_pp0_iter6_reg <= loc_V_reg_1498_pp0_iter5_reg;
        loc_V_reg_1498_pp0_iter7_reg <= loc_V_reg_1498_pp0_iter6_reg;
        loc_V_reg_1498_pp0_iter8_reg <= loc_V_reg_1498_pp0_iter7_reg;
        or_cond_44_reg_1576 <= or_cond_44_fu_581_p2;
        or_cond_44_reg_1576_pp0_iter10_reg <= or_cond_44_reg_1576_pp0_iter9_reg;
        or_cond_44_reg_1576_pp0_iter11_reg <= or_cond_44_reg_1576_pp0_iter10_reg;
        or_cond_44_reg_1576_pp0_iter12_reg <= or_cond_44_reg_1576_pp0_iter11_reg;
        or_cond_44_reg_1576_pp0_iter13_reg <= or_cond_44_reg_1576_pp0_iter12_reg;
        or_cond_44_reg_1576_pp0_iter14_reg <= or_cond_44_reg_1576_pp0_iter13_reg;
        or_cond_44_reg_1576_pp0_iter15_reg <= or_cond_44_reg_1576_pp0_iter14_reg;
        or_cond_44_reg_1576_pp0_iter16_reg <= or_cond_44_reg_1576_pp0_iter15_reg;
        or_cond_44_reg_1576_pp0_iter17_reg <= or_cond_44_reg_1576_pp0_iter16_reg;
        or_cond_44_reg_1576_pp0_iter18_reg <= or_cond_44_reg_1576_pp0_iter17_reg;
        or_cond_44_reg_1576_pp0_iter19_reg <= or_cond_44_reg_1576_pp0_iter18_reg;
        or_cond_44_reg_1576_pp0_iter20_reg <= or_cond_44_reg_1576_pp0_iter19_reg;
        or_cond_44_reg_1576_pp0_iter21_reg <= or_cond_44_reg_1576_pp0_iter20_reg;
        or_cond_44_reg_1576_pp0_iter22_reg <= or_cond_44_reg_1576_pp0_iter21_reg;
        or_cond_44_reg_1576_pp0_iter23_reg <= or_cond_44_reg_1576_pp0_iter22_reg;
        or_cond_44_reg_1576_pp0_iter24_reg <= or_cond_44_reg_1576_pp0_iter23_reg;
        or_cond_44_reg_1576_pp0_iter25_reg <= or_cond_44_reg_1576_pp0_iter24_reg;
        or_cond_44_reg_1576_pp0_iter26_reg <= or_cond_44_reg_1576_pp0_iter25_reg;
        or_cond_44_reg_1576_pp0_iter8_reg <= or_cond_44_reg_1576;
        or_cond_44_reg_1576_pp0_iter9_reg <= or_cond_44_reg_1576_pp0_iter8_reg;
        or_cond_i_reg_1886 <= or_cond_i_fu_1352_p2;
        or_cond_reg_1881 <= or_cond_fu_1301_p2;
        p_Result_13_1_i_reg_1793 <= {{grp_fu_992_p2[109:94]}};
        p_Result_13_1_i_reg_1793_pp0_iter24_reg <= p_Result_13_1_i_reg_1793;
        p_Result_13_2_i_reg_1798 <= {{grp_fu_992_p2[93:78]}};
        p_Result_13_2_i_reg_1798_pp0_iter24_reg <= p_Result_13_2_i_reg_1798;
        p_Result_1_i_reg_1788 <= {{grp_fu_992_p2[125:110]}};
        p_Result_30_reg_1493_pp0_iter2_reg <= p_Result_30_reg_1493_pp0_iter1_reg;
        p_Result_30_reg_1493_pp0_iter3_reg <= p_Result_30_reg_1493_pp0_iter2_reg;
        p_Result_30_reg_1493_pp0_iter4_reg <= p_Result_30_reg_1493_pp0_iter3_reg;
        p_Result_30_reg_1493_pp0_iter5_reg <= p_Result_30_reg_1493_pp0_iter4_reg;
        p_Result_30_reg_1493_pp0_iter6_reg <= p_Result_30_reg_1493_pp0_iter5_reg;
        p_Result_i1_reg_1803 <= {{grp_fu_992_p2[77:63]}};
        p_Result_i1_reg_1803_pp0_iter24_reg <= p_Result_i1_reg_1803;
        p_Result_i2_i_reg_1564 <= {{p_Val2_9_fu_446_p3[123:63]}};
        p_Result_i_reg_1618 <= {{p_Val2_15_fu_738_p3[62:56]}};
        p_Result_i_reg_1618_pp0_iter11_reg <= p_Result_i_reg_1618;
        p_Result_i_reg_1618_pp0_iter12_reg <= p_Result_i_reg_1618_pp0_iter11_reg;
        p_Result_s_reg_1588 <= p_Result_s_fu_614_p2;
        p_Result_s_reg_1588_pp0_iter10_reg <= p_Result_s_reg_1588_pp0_iter9_reg;
        p_Result_s_reg_1588_pp0_iter11_reg <= p_Result_s_reg_1588_pp0_iter10_reg;
        p_Result_s_reg_1588_pp0_iter12_reg <= p_Result_s_reg_1588_pp0_iter11_reg;
        p_Result_s_reg_1588_pp0_iter13_reg <= p_Result_s_reg_1588_pp0_iter12_reg;
        p_Result_s_reg_1588_pp0_iter14_reg <= p_Result_s_reg_1588_pp0_iter13_reg;
        p_Result_s_reg_1588_pp0_iter15_reg <= p_Result_s_reg_1588_pp0_iter14_reg;
        p_Result_s_reg_1588_pp0_iter16_reg <= p_Result_s_reg_1588_pp0_iter15_reg;
        p_Result_s_reg_1588_pp0_iter17_reg <= p_Result_s_reg_1588_pp0_iter16_reg;
        p_Result_s_reg_1588_pp0_iter18_reg <= p_Result_s_reg_1588_pp0_iter17_reg;
        p_Result_s_reg_1588_pp0_iter19_reg <= p_Result_s_reg_1588_pp0_iter18_reg;
        p_Result_s_reg_1588_pp0_iter20_reg <= p_Result_s_reg_1588_pp0_iter19_reg;
        p_Result_s_reg_1588_pp0_iter21_reg <= p_Result_s_reg_1588_pp0_iter20_reg;
        p_Result_s_reg_1588_pp0_iter22_reg <= p_Result_s_reg_1588_pp0_iter21_reg;
        p_Result_s_reg_1588_pp0_iter23_reg <= p_Result_s_reg_1588_pp0_iter22_reg;
        p_Result_s_reg_1588_pp0_iter24_reg <= p_Result_s_reg_1588_pp0_iter23_reg;
        p_Result_s_reg_1588_pp0_iter25_reg <= p_Result_s_reg_1588_pp0_iter24_reg;
        p_Result_s_reg_1588_pp0_iter26_reg <= p_Result_s_reg_1588_pp0_iter25_reg;
        p_Result_s_reg_1588_pp0_iter8_reg <= p_Result_s_reg_1588;
        p_Result_s_reg_1588_pp0_iter9_reg <= p_Result_s_reg_1588_pp0_iter8_reg;
        p_Val2_16_reg_1623 <= p_Val2_16_fu_755_p1;
        p_Val2_16_reg_1623_pp0_iter11_reg <= p_Val2_16_reg_1623;
        p_Val2_16_reg_1623_pp0_iter12_reg <= p_Val2_16_reg_1623_pp0_iter11_reg;
        p_Val2_16_reg_1623_pp0_iter13_reg <= p_Val2_16_reg_1623_pp0_iter12_reg;
        p_Val2_16_reg_1623_pp0_iter14_reg <= p_Val2_16_reg_1623_pp0_iter13_reg;
        p_Val2_20_reg_1688 <= fourth_order_double_4_q0;
        p_Val2_20_reg_1688_pp0_iter15_reg <= p_Val2_20_reg_1688;
        p_Val2_20_reg_1688_pp0_iter16_reg <= p_Val2_20_reg_1688_pp0_iter15_reg;
        p_Val2_20_reg_1688_pp0_iter17_reg <= p_Val2_20_reg_1688_pp0_iter16_reg;
        p_Val2_8_reg_1548 <= {{grp_fu_400_p2[166:43]}};
        p_Val2_9_reg_1559 <= p_Val2_9_fu_446_p3;
        p_Val2_9_reg_1559_pp0_iter8_reg <= p_Val2_9_reg_1559;
        r_V_reg_1768 <= r_V_fu_973_p2;
        result_V_reg_1783 <= {{grp_fu_992_p2[125:63]}};
        ret_V_9_reg_1896 <= ret_V_9_fu_1380_p3;
        sel_tmp6_i_reg_1876 <= sel_tmp6_i_fu_1295_p2;
        shift_2_1_i_reg_1842 <= shift_2_1_i_fu_1220_p2;
        shift_2_2_i_reg_1859 <= shift_2_2_i_fu_1241_p2;
        sin_basis_reg_1569 <= sin_basis_fu_463_p10;
        sin_basis_reg_1569_pp0_iter10_reg <= sin_basis_reg_1569_pp0_iter9_reg;
        sin_basis_reg_1569_pp0_iter11_reg <= sin_basis_reg_1569_pp0_iter10_reg;
        sin_basis_reg_1569_pp0_iter12_reg <= sin_basis_reg_1569_pp0_iter11_reg;
        sin_basis_reg_1569_pp0_iter13_reg <= sin_basis_reg_1569_pp0_iter12_reg;
        sin_basis_reg_1569_pp0_iter14_reg <= sin_basis_reg_1569_pp0_iter13_reg;
        sin_basis_reg_1569_pp0_iter15_reg <= sin_basis_reg_1569_pp0_iter14_reg;
        sin_basis_reg_1569_pp0_iter16_reg <= sin_basis_reg_1569_pp0_iter15_reg;
        sin_basis_reg_1569_pp0_iter17_reg <= sin_basis_reg_1569_pp0_iter16_reg;
        sin_basis_reg_1569_pp0_iter18_reg <= sin_basis_reg_1569_pp0_iter17_reg;
        sin_basis_reg_1569_pp0_iter19_reg <= sin_basis_reg_1569_pp0_iter18_reg;
        sin_basis_reg_1569_pp0_iter20_reg <= sin_basis_reg_1569_pp0_iter19_reg;
        sin_basis_reg_1569_pp0_iter21_reg <= sin_basis_reg_1569_pp0_iter20_reg;
        sin_basis_reg_1569_pp0_iter22_reg <= sin_basis_reg_1569_pp0_iter21_reg;
        sin_basis_reg_1569_pp0_iter23_reg <= sin_basis_reg_1569_pp0_iter22_reg;
        sin_basis_reg_1569_pp0_iter24_reg <= sin_basis_reg_1569_pp0_iter23_reg;
        sin_basis_reg_1569_pp0_iter25_reg <= sin_basis_reg_1569_pp0_iter24_reg;
        sin_basis_reg_1569_pp0_iter8_reg <= sin_basis_reg_1569;
        sin_basis_reg_1569_pp0_iter9_reg <= sin_basis_reg_1569_pp0_iter8_reg;
        tmp8_reg_1763 <= tmp8_fu_944_p2;
        tmp_10_1_i_reg_1853 <= tmp_10_1_i_fu_1235_p2;
        tmp_10_i1_reg_1753 <= {{grp_fu_855_p2[92:45]}};
        tmp_1_reg_1758 <= {{grp_fu_867_p2[74:38]}};
        tmp_37_i_reg_1640 <= {{grp_fu_772_p2[97:49]}};
        tmp_37_i_reg_1640_pp0_iter13_reg <= tmp_37_i_reg_1640;
        tmp_37_i_reg_1640_pp0_iter14_reg <= tmp_37_i_reg_1640_pp0_iter13_reg;
        tmp_39_i_reg_1678 <= {{grp_fu_791_p2[97:56]}};
        tmp_41_i_reg_1683 <= {{grp_fu_796_p2[97:63]}};
        tmp_4_reg_1542 <= tmp_4_fu_406_p2;
        tmp_4_reg_1542_pp0_iter3_reg <= tmp_4_reg_1542;
        tmp_4_reg_1542_pp0_iter4_reg <= tmp_4_reg_1542_pp0_iter3_reg;
        tmp_4_reg_1542_pp0_iter5_reg <= tmp_4_reg_1542_pp0_iter4_reg;
        tmp_4_reg_1542_pp0_iter6_reg <= tmp_4_reg_1542_pp0_iter5_reg;
        tmp_5_reg_1583 <= tmp_5_fu_586_p2;
        tmp_5_reg_1583_pp0_iter10_reg <= tmp_5_reg_1583_pp0_iter9_reg;
        tmp_5_reg_1583_pp0_iter11_reg <= tmp_5_reg_1583_pp0_iter10_reg;
        tmp_5_reg_1583_pp0_iter12_reg <= tmp_5_reg_1583_pp0_iter11_reg;
        tmp_5_reg_1583_pp0_iter13_reg <= tmp_5_reg_1583_pp0_iter12_reg;
        tmp_5_reg_1583_pp0_iter14_reg <= tmp_5_reg_1583_pp0_iter13_reg;
        tmp_5_reg_1583_pp0_iter15_reg <= tmp_5_reg_1583_pp0_iter14_reg;
        tmp_5_reg_1583_pp0_iter16_reg <= tmp_5_reg_1583_pp0_iter15_reg;
        tmp_5_reg_1583_pp0_iter17_reg <= tmp_5_reg_1583_pp0_iter16_reg;
        tmp_5_reg_1583_pp0_iter18_reg <= tmp_5_reg_1583_pp0_iter17_reg;
        tmp_5_reg_1583_pp0_iter19_reg <= tmp_5_reg_1583_pp0_iter18_reg;
        tmp_5_reg_1583_pp0_iter20_reg <= tmp_5_reg_1583_pp0_iter19_reg;
        tmp_5_reg_1583_pp0_iter21_reg <= tmp_5_reg_1583_pp0_iter20_reg;
        tmp_5_reg_1583_pp0_iter22_reg <= tmp_5_reg_1583_pp0_iter21_reg;
        tmp_5_reg_1583_pp0_iter23_reg <= tmp_5_reg_1583_pp0_iter22_reg;
        tmp_5_reg_1583_pp0_iter24_reg <= tmp_5_reg_1583_pp0_iter23_reg;
        tmp_5_reg_1583_pp0_iter25_reg <= tmp_5_reg_1583_pp0_iter24_reg;
        tmp_5_reg_1583_pp0_iter8_reg <= tmp_5_reg_1583;
        tmp_5_reg_1583_pp0_iter9_reg <= tmp_5_reg_1583_pp0_iter8_reg;
        tmp_8_1_i_reg_1847 <= tmp_8_1_i_fu_1230_p2;
        tmp_8_1_i_reg_1847_pp0_iter26_reg <= tmp_8_1_i_reg_1847;
        tmp_8_2_i_reg_1870 <= tmp_8_2_i_fu_1265_p2;
        tmp_8_i4_reg_1819 <= tmp_8_i4_fu_1099_p2;
        tmp_8_i4_reg_1819_pp0_iter25_reg <= tmp_8_i4_reg_1819;
        tmp_8_i4_reg_1819_pp0_iter26_reg <= tmp_8_i4_reg_1819_pp0_iter25_reg;
        tmp_8_i_reg_1748 <= {{grp_fu_843_p2[107:52]}};
        tmp_8_i_reg_1748_pp0_iter17_reg <= tmp_8_i_reg_1748;
        tmp_9_i7_reg_1825 <= tmp_9_i7_fu_1104_p2;
        tmp_9_i7_reg_1825_pp0_iter25_reg <= tmp_9_i7_reg_1825;
        tmp_9_reg_1891 <= tmp_9_fu_1376_p2;
        tmp_i1_reg_1628 <= {{p_Val2_15_fu_738_p3[55:7]}};
        tmp_i2_i_reg_1830 <= tmp_i2_i_fu_1194_p3;
        tmp_i3_i3_reg_1836 <= tmp_i3_i3_fu_1212_p3;
        tmp_i3_i3_reg_1836_pp0_iter26_reg <= tmp_i3_i3_reg_1836;
        tmp_i5_reg_1865 <= tmp_i5_fu_1257_p2;
        tmp_i_i_reg_1813 <= tmp_i_i_fu_1087_p3;
        tmp_i_i_reg_1813_pp0_iter25_reg <= tmp_i_i_reg_1813;
        tmp_s_reg_1743 <= {{p_Val2_2_fu_879_p2[59:31]}};
        tmp_s_reg_1743_pp0_iter16_reg <= tmp_s_reg_1743;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        closepath_reg_1511 <= closepath_fu_328_p2;
        closepath_reg_1511_pp0_iter1_reg <= closepath_reg_1511;
        loc_V_1_reg_1505 <= loc_V_1_fu_324_p1;
        loc_V_1_reg_1505_pp0_iter1_reg <= loc_V_1_reg_1505;
        loc_V_reg_1498 <= {{p_Val2_s_fu_302_p1[62:52]}};
        loc_V_reg_1498_pp0_iter1_reg <= loc_V_reg_1498;
        p_Result_30_reg_1493 <= p_Val2_s_fu_302_p1[32'd63];
        p_Result_30_reg_1493_pp0_iter1_reg <= p_Result_30_reg_1493;
        ret_V_reg_1527 <= {{r_V_3_fu_370_p2[255:86]}};
        tmp_20_reg_1522 <= tmp_20_fu_363_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((closepath_reg_1511_pp0_iter5_reg == 1'd0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_11_i_reg_1554 <= {{grp_fu_400_p2[169:167]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter27 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0))) begin
        ap_idle_pp0_0to26 = 1'b1;
    end else begin
        ap_idle_pp0_0to26 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to26 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fourth_order_double_4_ce0 = 1'b1;
    end else begin
        fourth_order_double_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fourth_order_double_5_ce0 = 1'b1;
    end else begin
        fourth_order_double_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fourth_order_double_6_ce0 = 1'b1;
    end else begin
        fourth_order_double_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fourth_order_double_7_ce0 = 1'b1;
    end else begin
        fourth_order_double_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fourth_order_double_s_ce0 = 1'b1;
    end else begin
        fourth_order_double_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_400_ce = 1'b1;
    end else begin
        grp_fu_400_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_772_ce = 1'b1;
    end else begin
        grp_fu_772_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_791_ce = 1'b1;
    end else begin
        grp_fu_791_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_796_ce = 1'b1;
    end else begin
        grp_fu_796_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_843_ce = 1'b1;
    end else begin
        grp_fu_843_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_855_ce = 1'b1;
    end else begin
        grp_fu_855_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_867_ce = 1'b1;
    end else begin
        grp_fu_867_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_992_ce = 1'b1;
    end else begin
        grp_fu_992_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ref_4oPi_table_256_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_256_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ex_V_fu_690_p2 = (storemerge_i_fu_662_p3 - tmp_15_i_fu_687_p1);

assign Ex_V_ret_s_fu_1247_p3 = ((sin_basis_reg_1569_pp0_iter25_reg[0:0] === 1'b1) ? Ex_V_reg_1606_pp0_iter25_reg : 11'd0);

assign Mx_V_read_assign_fu_979_p3 = ((sin_basis_reg_1569_pp0_iter18_reg[0:0] === 1'b1) ? Mx_V_reg_1599_pp0_iter18_reg : 63'd9223372036854775807);

assign Mx_zeros_V_fu_653_p1 = tmp_i3_i_fu_645_p3[5:0];

assign OP1_V_fu_769_p1 = tmp_i1_reg_1628;

assign OP2_V_fu_788_p1 = tmp_37_i_reg_1640;

assign addr_V_fu_340_p3 = ((closepath_fu_328_p2[0:0] === 1'b1) ? 11'd74 : expv_op_fu_334_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = p_Result_42_fu_1481_p4;

assign closepath_fu_328_p2 = ((loc_V_fu_314_p4 < 11'd1022) ? 1'b1 : 1'b0);

assign expv_op_fu_334_p2 = ($signed(11'd1101) + $signed(loc_V_fu_314_p4));

assign fourth_order_double_4_address0 = tmp_42_i_fu_808_p1;

assign fourth_order_double_5_address0 = tmp_42_i_fu_808_p1;

assign fourth_order_double_6_address0 = tmp_42_i_fu_808_p1;

assign fourth_order_double_7_address0 = tmp_42_i_fu_808_p1;

assign fourth_order_double_s_address0 = tmp_42_i_fu_808_p1;

assign grp_fu_400_p0 = grp_fu_400_p00;

assign grp_fu_400_p00 = p_Result_31_fu_386_p3;

assign grp_fu_400_p1 = grp_fu_400_p10;

assign grp_fu_400_p10 = ret_V_reg_1527;

assign grp_fu_772_p0 = OP1_V_fu_769_p1;

assign grp_fu_772_p1 = OP1_V_fu_769_p1;

assign grp_fu_791_p0 = OP2_V_fu_788_p1;

assign grp_fu_791_p1 = OP1_V_reg_1633_pp0_iter12_reg;

assign grp_fu_796_p0 = OP2_V_fu_788_p1;

assign grp_fu_796_p1 = OP2_V_fu_788_p1;

assign grp_fu_843_p1 = grp_fu_843_p10;

assign grp_fu_843_p10 = p_Val2_16_reg_1623_pp0_iter14_reg;

assign grp_fu_855_p1 = grp_fu_855_p10;

assign grp_fu_855_p10 = tmp_37_i_reg_1640_pp0_iter14_reg;

assign grp_fu_867_p0 = grp_fu_867_p00;

assign grp_fu_867_p00 = fourth_order_double_14_reg_1703;

assign grp_fu_867_p1 = grp_fu_867_p10;

assign grp_fu_867_p10 = tmp_39_i_reg_1678;

assign grp_fu_992_p0 = grp_fu_992_p00;

assign grp_fu_992_p00 = Mx_V_read_assign_fu_979_p3;

assign loc_V_1_fu_324_p1 = p_Val2_s_fu_302_p1[51:0];

assign loc_V_fu_314_p4 = {{p_Val2_s_fu_302_p1[62:52]}};

assign newSel3_fu_1307_p3 = ((sel_tmp6_i_fu_1295_p2[0:0] === 1'b1) ? shift_2_3_i_fu_1275_p2 : shift_2_1_i_reg_1842);

assign newSel4_fu_1314_p3 = ((tmp_i5_fu_1257_p2[0:0] === 1'b1) ? shift_2_2_i_reg_1859 : tmp_i_i_reg_1813_pp0_iter25_reg);

assign newSel5_fu_1320_p3 = ((or_cond_fu_1301_p2[0:0] === 1'b1) ? newSel3_fu_1307_p3 : newSel4_fu_1314_p3);

assign newexp_fu_1338_p2 = ($signed(tmp_6_cast_i_fu_1334_p1) - $signed(newSel5_fu_1320_p3));

assign not_or_cond1_fu_1461_p2 = (or_cond_44_reg_1576_pp0_iter26_reg ^ 1'd1);

assign not_or_cond_demorgan_fu_603_p2 = (tmp_4_reg_1542_pp0_iter6_reg & tmp_3_fu_576_p2);

assign not_or_cond_fu_608_p2 = (not_or_cond_demorgan_fu_603_p2 ^ 1'd1);

assign or_cond_44_fu_581_p2 = (tmp_4_reg_1542_pp0_iter6_reg & tmp_3_fu_576_p2);

assign or_cond_fu_1301_p2 = (sel_tmp6_i_fu_1295_p2 | sel_tmp3_i_fu_1284_p2);

assign or_cond_i_fu_1352_p2 = (tmp_9_i7_reg_1825_pp0_iter25_reg | tmp_25_fu_1344_p3);

assign out_exp_V_fu_1361_p3 = ((or_cond_i_fu_1352_p2[0:0] === 1'b1) ? 11'd0 : tmp_26_fu_1357_p1);

assign p_Result_31_fu_386_p3 = {{1'd1}, {loc_V_1_reg_1505_pp0_iter1_reg}};

assign p_Result_32_fu_620_p3 = {{p_Result_i2_i_reg_1564}, {1'd1}};

integer ap_tvar_int_0;

always @ (p_Result_32_fu_620_p3) begin
    for (ap_tvar_int_0 = 62 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 61 - 0) begin
            p_Result_33_fu_627_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_33_fu_627_p4[ap_tvar_int_0] = p_Result_32_fu_620_p3[61 - ap_tvar_int_0];
        end
    end
end

assign p_Result_34_fu_637_p3 = {{2'd3}, {p_Result_33_fu_627_p4}};

assign p_Result_35_fu_802_p3 = {{sin_basis_reg_1569_pp0_iter12_reg}, {p_Result_i_reg_1618_pp0_iter12_reg}};

assign p_Result_36_fu_1154_p5 = {{tmp_3_i_fu_1147_p3}, {ap_const_lv32_0[15:0]}};

integer ap_tvar_int_1;

always @ (p_Val2_24_fu_1065_p5) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            p_Result_37_fu_1077_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_37_fu_1077_p4[ap_tvar_int_1] = p_Val2_24_fu_1065_p5[31 - ap_tvar_int_1];
        end
    end
end

integer ap_tvar_int_2;

always @ (p_Val2_25_fu_1116_p5) begin
    for (ap_tvar_int_2 = 32 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 31 - 0) begin
            p_Result_38_fu_1166_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_38_fu_1166_p4[ap_tvar_int_2] = p_Val2_25_fu_1116_p5[31 - ap_tvar_int_2];
        end
    end
end

integer ap_tvar_int_3;

always @ (p_Val2_26_fu_1135_p5) begin
    for (ap_tvar_int_3 = 32 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 31 - 0) begin
            p_Result_39_fu_1184_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            p_Result_39_fu_1184_p4[ap_tvar_int_3] = p_Val2_26_fu_1135_p5[31 - ap_tvar_int_3];
        end
    end
end

integer ap_tvar_int_4;

always @ (p_Result_36_fu_1154_p5) begin
    for (ap_tvar_int_4 = 32 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 31 - 0) begin
            p_Result_40_fu_1202_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            p_Result_40_fu_1202_p4[ap_tvar_int_4] = p_Result_36_fu_1154_p5[31 - ap_tvar_int_4];
        end
    end
end

assign p_Result_41_fu_485_p3 = {{p_Result_30_reg_1493_pp0_iter6_reg}, {p_Val2_34_fu_431_p3}};

assign p_Result_42_fu_1481_p4 = {{{p_Result_s_reg_1588_pp0_iter26_reg}, {ret_V_9_reg_1896}}, {ret_V_10_fu_1474_p3}};

assign p_Result_i_i_fu_348_p4 = {{addr_V_fu_340_p3[10:7]}};

assign p_Result_s_fu_614_p2 = (p_results_sign_V_ret_fu_597_p2 & not_or_cond_fu_608_p2);

assign p_Val2_14_fu_672_p2 = p_Val2_9_reg_1559_pp0_iter8_reg << tmp_12_i_fu_669_p1;

assign p_Val2_15_fu_738_p3 = ((isNeg_reg_1612[0:0] === 1'b1) ? tmp_19_i_fu_728_p2 : tmp_20_i_fu_733_p2);

assign p_Val2_16_fu_755_p1 = p_Val2_15_fu_738_p3[55:0];

assign p_Val2_21_fu_950_p3 = {{p_Val2_20_reg_1688_pp0_iter17_reg}, {4'd0}};

assign p_Val2_24_fu_1065_p5 = {{tmp_i_43_fu_1058_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_25_fu_1116_p5 = {{tmp_1_i_fu_1109_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_26_fu_1135_p5 = {{tmp_2_i_fu_1128_p3}, {ap_const_lv32_0[14:0]}};

assign p_Val2_2_fu_879_p0 = p_Val2_2_fu_879_p00;

assign p_Val2_2_fu_879_p00 = fourth_order_double_16_reg_1708;

assign p_Val2_2_fu_879_p1 = p_Val2_2_fu_879_p10;

assign p_Val2_2_fu_879_p10 = tmp_41_i_reg_1683;

assign p_Val2_2_fu_879_p2 = (p_Val2_2_fu_879_p0 * p_Val2_2_fu_879_p1);

assign p_Val2_34_fu_431_p3 = ((closepath_reg_1511_pp0_iter6_reg[0:0] === 1'b1) ? 3'd0 : tmp_11_i_reg_1554);

assign p_Val2_35_fu_1454_p3 = ((or_cond_i_reg_1886[0:0] === 1'b1) ? 52'd0 : tmp_16_fu_1447_p3);

assign p_Val2_9_fu_446_p3 = ((tmp_21_fu_437_p1[0:0] === 1'b1) ? p_Val2_i_fu_441_p2 : p_Val2_8_reg_1548);

assign p_Val2_i_fu_441_p2 = (124'd0 - p_Val2_8_reg_1548);

assign p_Val2_s_fu_302_p1 = t_in;

assign p_results_exp_V_ret_fu_1369_p3 = ((or_cond_44_reg_1576_pp0_iter25_reg[0:0] === 1'b1) ? 11'd1023 : 11'd2047);

assign p_results_sig_V_ret_c_fu_1466_p3 = ((not_or_cond1_fu_1461_p2[0:0] === 1'b1) ? 52'd4503599627370495 : 52'd0);

assign p_results_sign_V_ret_fu_597_p2 = (tmp_8_fu_591_p2 & tmp_2_fu_568_p3);

assign r_V_3_fu_370_p2 = ref_4oPi_table_256_V_q0 << tmp_4_i_i_fu_367_p1;

assign r_V_fu_973_p2 = ($signed(tmp_fu_964_p2) + $signed(tmp8_cast_fu_970_p1));

assign ref_4oPi_table_256_V_address0 = tmp_2_i_i_fu_358_p1;

assign ret_V_10_fu_1474_p3 = ((tmp_9_reg_1891[0:0] === 1'b1) ? p_results_sig_V_ret_c_fu_1466_p3 : p_Val2_35_fu_1454_p3);

assign ret_V_9_fu_1380_p3 = ((tmp_9_fu_1376_p2[0:0] === 1'b1) ? p_results_exp_V_ret_fu_1369_p3 : out_exp_V_fu_1361_p3);

assign rhs_V_fu_1253_p1 = $signed(Ex_V_ret_s_fu_1247_p3);

assign sel_tmp2_i_fu_1279_p2 = (tmp_10_1_i_reg_1853 ^ 1'd1);

assign sel_tmp3_i_fu_1284_p2 = (tmp_i5_fu_1257_p2 & sel_tmp2_i_fu_1279_p2);

assign sel_tmp6_i_fu_1295_p2 = (tmp_i5_fu_1257_p2 & tmp2_fu_1290_p2);

assign sh_assign_1_i_cast_fu_720_p1 = $signed(sh_assign_fu_713_p3);

assign sh_assign_fu_713_p3 = ((isNeg_reg_1612[0:0] === 1'b1) ? tmp_17_i_fu_707_p2 : sh_i_cast_fu_704_p1);

assign sh_i_cast_fu_704_p1 = Ex_V_reg_1606;

assign shift_2_1_i_fu_1220_p2 = (32'd16 + tmp_i1_i_fu_1176_p3);

assign shift_2_2_i_fu_1241_p2 = (tmp_i2_i_fu_1194_p3 + shift_2_1_i_fu_1220_p2);

assign shift_2_3_i_fu_1275_p2 = (tmp_i3_i3_reg_1836 + shift_2_2_i_reg_1859);

assign storemerge_i_fu_662_p3 = ((closepath_reg_1511_pp0_iter8_reg[0:0] === 1'b1) ? tmp_i_fu_657_p2 : 11'd0);

assign tmp2_fu_1290_p2 = (tmp_10_2_i_fu_1270_p2 & tmp_10_1_i_reg_1853);

assign tmp8_cast_fu_970_p1 = $signed(tmp8_reg_1763);

assign tmp8_fu_944_p2 = ($signed(tmp_47_i_cast_cast_fu_928_p1) + $signed(tmp9_cast_fu_940_p1));

assign tmp9_cast_fu_940_p1 = tmp9_fu_934_p2;

assign tmp9_fu_934_p2 = (tmp_51_i_cast_cast_fu_931_p1 + tmp_12_i1_fu_925_p1);

assign tmp_10_1_i_fu_1235_p2 = ((tmp_i1_i_fu_1176_p3 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_10_2_i_fu_1270_p2 = ((tmp_i2_i_reg_1830 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_10_fu_1396_p4 = {{tmp_8_3_i_fu_1391_p2[61:10]}};

assign tmp_11_fu_1406_p4 = {{tmp_8_1_i_reg_1847_pp0_iter26_reg[61:10]}};

assign tmp_12_fu_1415_p3 = ((sel_tmp6_i_reg_1876[0:0] === 1'b1) ? tmp_10_fu_1396_p4 : tmp_11_fu_1406_p4);

assign tmp_12_i1_fu_925_p1 = tmp_1_reg_1758;

assign tmp_12_i_fu_669_p1 = Mx_zeros_V_reg_1593;

assign tmp_13_fu_1422_p4 = {{tmp_8_2_i_reg_1870[61:10]}};

assign tmp_14_fu_1431_p4 = {{tmp_8_i4_reg_1819_pp0_iter26_reg[61:10]}};

assign tmp_15_fu_1440_p3 = ((tmp_i5_reg_1865[0:0] === 1'b1) ? tmp_13_fu_1422_p4 : tmp_14_fu_1431_p4);

assign tmp_15_i_fu_687_p1 = Mx_zeros_V_reg_1593;

assign tmp_16_fu_1447_p3 = ((or_cond_reg_1881[0:0] === 1'b1) ? tmp_12_fu_1415_p3 : tmp_15_fu_1440_p3);

assign tmp_17_i_fu_707_p2 = ($signed(12'd0) - $signed(sh_i_cast_fu_704_p1));

assign tmp_18_i_fu_724_p1 = $unsigned(sh_assign_1_i_cast_fu_720_p1);

assign tmp_19_i_fu_728_p2 = Mx_V_reg_1599 >> tmp_18_i_fu_724_p1;

assign tmp_1_i_fu_1109_p3 = {{p_Result_13_1_i_reg_1793_pp0_iter24_reg}, {1'd1}};

assign tmp_20_fu_363_p1 = addr_V_fu_340_p3[6:0];

assign tmp_20_i_fu_733_p2 = Mx_V_reg_1599 << tmp_18_i_fu_724_p1;

assign tmp_21_fu_437_p1 = p_Val2_34_fu_431_p3[0:0];

assign tmp_25_fu_1344_p3 = newexp_fu_1338_p2[32'd31];

assign tmp_26_fu_1357_p1 = newexp_fu_1338_p2[10:0];

assign tmp_2_fu_568_p3 = ((sin_basis_fu_463_p10[0:0] === 1'b1) ? tmp_6_fu_492_p18 : tmp_7_fu_530_p18);

assign tmp_2_i_fu_1128_p3 = {{p_Result_13_2_i_reg_1798_pp0_iter24_reg}, {1'd1}};

assign tmp_2_i_i_fu_358_p1 = p_Result_i_i_fu_348_p4;

assign tmp_3_fu_576_p2 = ((loc_V_reg_1498_pp0_iter6_reg == 11'd0) ? 1'b1 : 1'b0);

assign tmp_3_i_fu_1147_p3 = {{p_Result_i1_reg_1803_pp0_iter24_reg}, {1'd1}};

assign tmp_42_i_fu_808_p1 = p_Result_35_fu_802_p3;

assign tmp_44_i_fu_957_p1 = $signed(p_Val2_21_fu_950_p3);

assign tmp_45_i_fu_961_p1 = $signed(tmp_8_i_reg_1748_pp0_iter17_reg);

assign tmp_47_i_cast_cast_fu_928_p1 = $signed(tmp_10_i1_reg_1753);

assign tmp_4_1_cast_i_fu_1226_p1 = tmp_i1_i_fu_1176_p3;

assign tmp_4_2_cast_i_fu_1262_p1 = tmp_i2_i_reg_1830;

assign tmp_4_3_cast_i_fu_1388_p1 = tmp_i3_i3_reg_1836_pp0_iter26_reg;

assign tmp_4_cast_i_fu_1095_p1 = tmp_i_i_fu_1087_p3;

assign tmp_4_fu_406_p2 = ((loc_V_1_reg_1505_pp0_iter1_reg == 52'd0) ? 1'b1 : 1'b0);

assign tmp_4_i_i_fu_367_p1 = tmp_20_reg_1522;

assign tmp_51_i_cast_cast_fu_931_p1 = tmp_s_reg_1743_pp0_iter16_reg;

assign tmp_5_fu_586_p2 = ((loc_V_reg_1498_pp0_iter6_reg == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_6_cast_i_fu_1334_p1 = $signed(tmp_6_i_fu_1328_p2);

assign tmp_6_i_fu_1328_p2 = ($signed(12'd1023) + $signed(rhs_V_fu_1253_p1));

assign tmp_8_1_i_fu_1230_p2 = tmp_8_i4_reg_1819 << tmp_4_1_cast_i_fu_1226_p1;

assign tmp_8_2_i_fu_1265_p2 = tmp_8_1_i_reg_1847 << tmp_4_2_cast_i_fu_1262_p1;

assign tmp_8_3_i_fu_1391_p2 = tmp_8_2_i_reg_1870 << tmp_4_3_cast_i_fu_1388_p1;

assign tmp_8_fu_591_p2 = (tmp_5_fu_586_p2 ^ 1'd1);

assign tmp_8_i4_fu_1099_p2 = in_V_cast_i_reg_1808 << tmp_4_cast_i_fu_1095_p1;

assign tmp_9_fu_1376_p2 = (tmp_5_reg_1583_pp0_iter25_reg | or_cond_44_reg_1576_pp0_iter25_reg);

assign tmp_9_i7_fu_1104_p2 = ((result_V_reg_1783 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_fu_964_p2 = ($signed(tmp_45_i_fu_961_p1) + $signed(tmp_44_i_fu_957_p1));


always @ (p_Result_38_fu_1166_p4) begin
    if (p_Result_38_fu_1166_p4[0] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd0;
    end else if (p_Result_38_fu_1166_p4[1] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd1;
    end else if (p_Result_38_fu_1166_p4[2] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd2;
    end else if (p_Result_38_fu_1166_p4[3] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd3;
    end else if (p_Result_38_fu_1166_p4[4] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd4;
    end else if (p_Result_38_fu_1166_p4[5] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd5;
    end else if (p_Result_38_fu_1166_p4[6] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd6;
    end else if (p_Result_38_fu_1166_p4[7] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd7;
    end else if (p_Result_38_fu_1166_p4[8] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd8;
    end else if (p_Result_38_fu_1166_p4[9] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd9;
    end else if (p_Result_38_fu_1166_p4[10] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd10;
    end else if (p_Result_38_fu_1166_p4[11] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd11;
    end else if (p_Result_38_fu_1166_p4[12] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd12;
    end else if (p_Result_38_fu_1166_p4[13] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd13;
    end else if (p_Result_38_fu_1166_p4[14] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd14;
    end else if (p_Result_38_fu_1166_p4[15] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd15;
    end else if (p_Result_38_fu_1166_p4[16] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd16;
    end else if (p_Result_38_fu_1166_p4[17] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd17;
    end else if (p_Result_38_fu_1166_p4[18] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd18;
    end else if (p_Result_38_fu_1166_p4[19] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd19;
    end else if (p_Result_38_fu_1166_p4[20] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd20;
    end else if (p_Result_38_fu_1166_p4[21] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd21;
    end else if (p_Result_38_fu_1166_p4[22] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd22;
    end else if (p_Result_38_fu_1166_p4[23] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd23;
    end else if (p_Result_38_fu_1166_p4[24] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd24;
    end else if (p_Result_38_fu_1166_p4[25] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd25;
    end else if (p_Result_38_fu_1166_p4[26] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd26;
    end else if (p_Result_38_fu_1166_p4[27] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd27;
    end else if (p_Result_38_fu_1166_p4[28] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd28;
    end else if (p_Result_38_fu_1166_p4[29] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd29;
    end else if (p_Result_38_fu_1166_p4[30] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd30;
    end else if (p_Result_38_fu_1166_p4[31] == 1'b1) begin
        tmp_i1_i_fu_1176_p3 = 32'd31;
    end else begin
        tmp_i1_i_fu_1176_p3 = 32'd32;
    end
end


always @ (p_Result_39_fu_1184_p4) begin
    if (p_Result_39_fu_1184_p4[0] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd0;
    end else if (p_Result_39_fu_1184_p4[1] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd1;
    end else if (p_Result_39_fu_1184_p4[2] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd2;
    end else if (p_Result_39_fu_1184_p4[3] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd3;
    end else if (p_Result_39_fu_1184_p4[4] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd4;
    end else if (p_Result_39_fu_1184_p4[5] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd5;
    end else if (p_Result_39_fu_1184_p4[6] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd6;
    end else if (p_Result_39_fu_1184_p4[7] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd7;
    end else if (p_Result_39_fu_1184_p4[8] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd8;
    end else if (p_Result_39_fu_1184_p4[9] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd9;
    end else if (p_Result_39_fu_1184_p4[10] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd10;
    end else if (p_Result_39_fu_1184_p4[11] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd11;
    end else if (p_Result_39_fu_1184_p4[12] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd12;
    end else if (p_Result_39_fu_1184_p4[13] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd13;
    end else if (p_Result_39_fu_1184_p4[14] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd14;
    end else if (p_Result_39_fu_1184_p4[15] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd15;
    end else if (p_Result_39_fu_1184_p4[16] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd16;
    end else if (p_Result_39_fu_1184_p4[17] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd17;
    end else if (p_Result_39_fu_1184_p4[18] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd18;
    end else if (p_Result_39_fu_1184_p4[19] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd19;
    end else if (p_Result_39_fu_1184_p4[20] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd20;
    end else if (p_Result_39_fu_1184_p4[21] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd21;
    end else if (p_Result_39_fu_1184_p4[22] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd22;
    end else if (p_Result_39_fu_1184_p4[23] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd23;
    end else if (p_Result_39_fu_1184_p4[24] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd24;
    end else if (p_Result_39_fu_1184_p4[25] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd25;
    end else if (p_Result_39_fu_1184_p4[26] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd26;
    end else if (p_Result_39_fu_1184_p4[27] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd27;
    end else if (p_Result_39_fu_1184_p4[28] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd28;
    end else if (p_Result_39_fu_1184_p4[29] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd29;
    end else if (p_Result_39_fu_1184_p4[30] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd30;
    end else if (p_Result_39_fu_1184_p4[31] == 1'b1) begin
        tmp_i2_i_fu_1194_p3 = 32'd31;
    end else begin
        tmp_i2_i_fu_1194_p3 = 32'd32;
    end
end


always @ (p_Result_40_fu_1202_p4) begin
    if (p_Result_40_fu_1202_p4[0] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd0;
    end else if (p_Result_40_fu_1202_p4[1] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd1;
    end else if (p_Result_40_fu_1202_p4[2] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd2;
    end else if (p_Result_40_fu_1202_p4[3] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd3;
    end else if (p_Result_40_fu_1202_p4[4] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd4;
    end else if (p_Result_40_fu_1202_p4[5] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd5;
    end else if (p_Result_40_fu_1202_p4[6] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd6;
    end else if (p_Result_40_fu_1202_p4[7] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd7;
    end else if (p_Result_40_fu_1202_p4[8] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd8;
    end else if (p_Result_40_fu_1202_p4[9] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd9;
    end else if (p_Result_40_fu_1202_p4[10] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd10;
    end else if (p_Result_40_fu_1202_p4[11] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd11;
    end else if (p_Result_40_fu_1202_p4[12] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd12;
    end else if (p_Result_40_fu_1202_p4[13] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd13;
    end else if (p_Result_40_fu_1202_p4[14] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd14;
    end else if (p_Result_40_fu_1202_p4[15] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd15;
    end else if (p_Result_40_fu_1202_p4[16] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd16;
    end else if (p_Result_40_fu_1202_p4[17] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd17;
    end else if (p_Result_40_fu_1202_p4[18] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd18;
    end else if (p_Result_40_fu_1202_p4[19] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd19;
    end else if (p_Result_40_fu_1202_p4[20] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd20;
    end else if (p_Result_40_fu_1202_p4[21] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd21;
    end else if (p_Result_40_fu_1202_p4[22] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd22;
    end else if (p_Result_40_fu_1202_p4[23] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd23;
    end else if (p_Result_40_fu_1202_p4[24] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd24;
    end else if (p_Result_40_fu_1202_p4[25] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd25;
    end else if (p_Result_40_fu_1202_p4[26] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd26;
    end else if (p_Result_40_fu_1202_p4[27] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd27;
    end else if (p_Result_40_fu_1202_p4[28] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd28;
    end else if (p_Result_40_fu_1202_p4[29] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd29;
    end else if (p_Result_40_fu_1202_p4[30] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd30;
    end else if (p_Result_40_fu_1202_p4[31] == 1'b1) begin
        tmp_i3_i3_fu_1212_p3 = 32'd31;
    end else begin
        tmp_i3_i3_fu_1212_p3 = 32'd32;
    end
end


always @ (p_Result_34_fu_637_p3) begin
    if (p_Result_34_fu_637_p3[0] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd0;
    end else if (p_Result_34_fu_637_p3[1] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd1;
    end else if (p_Result_34_fu_637_p3[2] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd2;
    end else if (p_Result_34_fu_637_p3[3] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd3;
    end else if (p_Result_34_fu_637_p3[4] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd4;
    end else if (p_Result_34_fu_637_p3[5] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd5;
    end else if (p_Result_34_fu_637_p3[6] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd6;
    end else if (p_Result_34_fu_637_p3[7] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd7;
    end else if (p_Result_34_fu_637_p3[8] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd8;
    end else if (p_Result_34_fu_637_p3[9] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd9;
    end else if (p_Result_34_fu_637_p3[10] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd10;
    end else if (p_Result_34_fu_637_p3[11] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd11;
    end else if (p_Result_34_fu_637_p3[12] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd12;
    end else if (p_Result_34_fu_637_p3[13] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd13;
    end else if (p_Result_34_fu_637_p3[14] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd14;
    end else if (p_Result_34_fu_637_p3[15] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd15;
    end else if (p_Result_34_fu_637_p3[16] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd16;
    end else if (p_Result_34_fu_637_p3[17] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd17;
    end else if (p_Result_34_fu_637_p3[18] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd18;
    end else if (p_Result_34_fu_637_p3[19] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd19;
    end else if (p_Result_34_fu_637_p3[20] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd20;
    end else if (p_Result_34_fu_637_p3[21] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd21;
    end else if (p_Result_34_fu_637_p3[22] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd22;
    end else if (p_Result_34_fu_637_p3[23] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd23;
    end else if (p_Result_34_fu_637_p3[24] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd24;
    end else if (p_Result_34_fu_637_p3[25] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd25;
    end else if (p_Result_34_fu_637_p3[26] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd26;
    end else if (p_Result_34_fu_637_p3[27] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd27;
    end else if (p_Result_34_fu_637_p3[28] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd28;
    end else if (p_Result_34_fu_637_p3[29] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd29;
    end else if (p_Result_34_fu_637_p3[30] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd30;
    end else if (p_Result_34_fu_637_p3[31] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd31;
    end else if (p_Result_34_fu_637_p3[32] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd32;
    end else if (p_Result_34_fu_637_p3[33] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd33;
    end else if (p_Result_34_fu_637_p3[34] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd34;
    end else if (p_Result_34_fu_637_p3[35] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd35;
    end else if (p_Result_34_fu_637_p3[36] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd36;
    end else if (p_Result_34_fu_637_p3[37] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd37;
    end else if (p_Result_34_fu_637_p3[38] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd38;
    end else if (p_Result_34_fu_637_p3[39] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd39;
    end else if (p_Result_34_fu_637_p3[40] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd40;
    end else if (p_Result_34_fu_637_p3[41] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd41;
    end else if (p_Result_34_fu_637_p3[42] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd42;
    end else if (p_Result_34_fu_637_p3[43] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd43;
    end else if (p_Result_34_fu_637_p3[44] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd44;
    end else if (p_Result_34_fu_637_p3[45] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd45;
    end else if (p_Result_34_fu_637_p3[46] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd46;
    end else if (p_Result_34_fu_637_p3[47] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd47;
    end else if (p_Result_34_fu_637_p3[48] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd48;
    end else if (p_Result_34_fu_637_p3[49] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd49;
    end else if (p_Result_34_fu_637_p3[50] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd50;
    end else if (p_Result_34_fu_637_p3[51] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd51;
    end else if (p_Result_34_fu_637_p3[52] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd52;
    end else if (p_Result_34_fu_637_p3[53] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd53;
    end else if (p_Result_34_fu_637_p3[54] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd54;
    end else if (p_Result_34_fu_637_p3[55] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd55;
    end else if (p_Result_34_fu_637_p3[56] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd56;
    end else if (p_Result_34_fu_637_p3[57] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd57;
    end else if (p_Result_34_fu_637_p3[58] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd58;
    end else if (p_Result_34_fu_637_p3[59] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd59;
    end else if (p_Result_34_fu_637_p3[60] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd60;
    end else if (p_Result_34_fu_637_p3[61] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd61;
    end else if (p_Result_34_fu_637_p3[62] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd62;
    end else if (p_Result_34_fu_637_p3[63] == 1'b1) begin
        tmp_i3_i_fu_645_p3 = 64'd63;
    end else begin
        tmp_i3_i_fu_645_p3 = 64'd64;
    end
end

assign tmp_i5_fu_1257_p2 = ((tmp_i_i_reg_1813_pp0_iter25_reg == 32'd16) ? 1'b1 : 1'b0);

assign tmp_i_43_fu_1058_p3 = {{p_Result_1_i_reg_1788}, {1'd1}};

assign tmp_i_fu_657_p2 = ($signed(11'd1027) + $signed(loc_V_reg_1498_pp0_iter8_reg));


always @ (p_Result_37_fu_1077_p4) begin
    if (p_Result_37_fu_1077_p4[0] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd0;
    end else if (p_Result_37_fu_1077_p4[1] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd1;
    end else if (p_Result_37_fu_1077_p4[2] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd2;
    end else if (p_Result_37_fu_1077_p4[3] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd3;
    end else if (p_Result_37_fu_1077_p4[4] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd4;
    end else if (p_Result_37_fu_1077_p4[5] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd5;
    end else if (p_Result_37_fu_1077_p4[6] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd6;
    end else if (p_Result_37_fu_1077_p4[7] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd7;
    end else if (p_Result_37_fu_1077_p4[8] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd8;
    end else if (p_Result_37_fu_1077_p4[9] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd9;
    end else if (p_Result_37_fu_1077_p4[10] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd10;
    end else if (p_Result_37_fu_1077_p4[11] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd11;
    end else if (p_Result_37_fu_1077_p4[12] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd12;
    end else if (p_Result_37_fu_1077_p4[13] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd13;
    end else if (p_Result_37_fu_1077_p4[14] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd14;
    end else if (p_Result_37_fu_1077_p4[15] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd15;
    end else if (p_Result_37_fu_1077_p4[16] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd16;
    end else if (p_Result_37_fu_1077_p4[17] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd17;
    end else if (p_Result_37_fu_1077_p4[18] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd18;
    end else if (p_Result_37_fu_1077_p4[19] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd19;
    end else if (p_Result_37_fu_1077_p4[20] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd20;
    end else if (p_Result_37_fu_1077_p4[21] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd21;
    end else if (p_Result_37_fu_1077_p4[22] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd22;
    end else if (p_Result_37_fu_1077_p4[23] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd23;
    end else if (p_Result_37_fu_1077_p4[24] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd24;
    end else if (p_Result_37_fu_1077_p4[25] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd25;
    end else if (p_Result_37_fu_1077_p4[26] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd26;
    end else if (p_Result_37_fu_1077_p4[27] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd27;
    end else if (p_Result_37_fu_1077_p4[28] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd28;
    end else if (p_Result_37_fu_1077_p4[29] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd29;
    end else if (p_Result_37_fu_1077_p4[30] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd30;
    end else if (p_Result_37_fu_1077_p4[31] == 1'b1) begin
        tmp_i_i_fu_1087_p3 = 32'd31;
    end else begin
        tmp_i_i_fu_1087_p3 = 32'd32;
    end
end

always @ (posedge ap_clk) begin
    OP1_V_reg_1633[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
    OP1_V_reg_1633_pp0_iter12_reg[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //sin_or_cos_double_s
